target("ffl.icp20100")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/icp20100.c", "src/ffl_icp20100.c")
    add_headerfiles("include/*.h", "include/(ffl/*.h)")
    add_includedirs("include", {public = true})
    add_deps("ffl.atomic", "ffl.driver_port")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.icp20100.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/icp20100_cxx_compile.cpp")
    add_deps("ffl.icp20100")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")

target("ffl.icp20100.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/icp20100_test.c")
    add_deps("ffl.icp20100")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")
