target("ffl.driver_port")
    set_kind("headeronly")
    set_default(false)
    set_languages("c11", "cxx17")
    add_headerfiles("include/ffl/*.h")
    add_includedirs("include", {public = true})

target("ffl.driver_port.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/driver_port_test.c")
    add_deps("ffl.driver_port")
    add_tests("default")

target("ffl.driver_port.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/driver_port_cxx_test.cpp")
    add_deps("ffl.driver_port")
    add_tests("default")
