target("ffl.atomic")
    set_kind("headeronly")
    set_default(false)
    set_languages("c11", "cxx17")
    add_headerfiles("include/ffl_atomic.h")
    add_includedirs("include", {public = true})

target("ffl.atomic.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/atomic_smoke.c")
    add_deps("ffl.atomic")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.atomic.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/atomic_cxx_smoke.cpp")
    add_deps("ffl.atomic")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")
