target("ffl.impact_displacement")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/*.c")
    add_headerfiles("include/ffl/impact_displacement.h")
    add_includedirs("include", {public = true})
    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.impact_displacement.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/impact_displacement_smoke.c")
    add_deps("ffl.impact_displacement")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.impact_displacement.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/impact_displacement_cxx_smoke.cpp")
    add_deps("ffl.impact_displacement")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")
