target("ffl.icm42688p")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/imu_icm42688p.c", "src/ffl_icm42688p.c")
    add_headerfiles("include/*.h", "include/(ffl/*.h)")
    add_includedirs("include", {public = true})
    add_deps("ffl.atomic", "ffl.driver_port", "ffl.imu_common")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.icm42688p.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/icm42688p_cxx_compile.cpp")
    add_deps("ffl.icm42688p")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")

target("ffl.icm42688p.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/icm42688p_test.c")
    add_deps("ffl.icm42688p")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")
