target("ffl.protothreads")
    set_kind("headeronly")
    set_default(false)
    set_languages("c11", "cxx17")
    add_headerfiles("include/protothreads.h")
    add_includedirs("include", {public = true})
