target("ffl.sht40")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/sht40_core.c", "src/sht40_sync.c", "src/sht40_async.c", "src/ffl_sht40.c")
    add_headerfiles("include/*.h", "include/(ffl/*.h)")
    add_includedirs("include", {public = true})
    add_deps("ffl.atomic", "ffl.driver_port")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.sht40.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/sht40_crc_test.c")
    add_deps("ffl.sht40")
    add_tests("default")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.sht40.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/sht40_cxx_compile.cpp")
    add_deps("ffl.sht40")
    add_tests("default")

    add_cxxflags("-Wall", "-Wextra", "-Werror")
