target("ffl.qmc5883p")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/qmc5883p.c", "src/ffl_qmc5883p.c")
    add_headerfiles("include/*.h", "include/(ffl/*.h)")
    add_includedirs("include", {public = true})
    add_deps("ffl.atomic", "ffl.driver_port")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.qmc5883p.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/qmc5883p_cxx_compile.cpp")
    add_deps("ffl.qmc5883p")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")

target("ffl.qmc5883p.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/qmc5883p_test.c")
    add_deps("ffl.qmc5883p")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")
