target("ffl.qmi8658a")
    set_kind("object")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("src/imu_qmi8658a.c", "src/ffl_qmi8658a.c")
    add_headerfiles("include/*.h", "include/(ffl/*.h)")
    add_includedirs("include", {public = true})
    add_deps("ffl.atomic", "ffl.driver_port", "ffl.imu_common")

    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.qmi8658a.test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/qmi8658a_test.c")
    add_deps("ffl.qmi8658a")
    add_tests("default")
    add_cflags("-Wall", "-Wextra", "-Werror")

target("ffl.qmi8658a.cxx-test")
    set_kind("binary")
    set_default(false)
    set_languages("c11", "cxx17")
    add_files("test/qmi8658a_cxx_compile.cpp")
    add_deps("ffl.qmi8658a")
    add_tests("default")
    add_cxxflags("-Wall", "-Wextra", "-Werror")
